<?php

/**
 * Basepms_email_log
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $addr_to
 * @property string $addr_from
 * @property string $subject
 * @property clob $body
 * 
 * @method string        getAddrTo()    Returns the current record's "addr_to" value
 * @method string        getAddrFrom()  Returns the current record's "addr_from" value
 * @method string        getSubject()   Returns the current record's "subject" value
 * @method clob          getBody()      Returns the current record's "body" value
 * @method pms_email_log setAddrTo()    Sets the current record's "addr_to" value
 * @method pms_email_log setAddrFrom()  Sets the current record's "addr_from" value
 * @method pms_email_log setSubject()   Sets the current record's "subject" value
 * @method pms_email_log setBody()      Sets the current record's "body" value
 * 
 * @package    hypertech_booking
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepms_email_log extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pms_email_log');
        $this->hasColumn('addr_to', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('addr_from', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('subject', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}