<?php

/**
 * BaseBooking
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $cover
 * @property string $director
 * @property integer $address_id
 * @property Doctrine_Collection $Actor
 * @property Address $Address
 * @property Doctrine_Collection $BookingPassenger
 * 
 * @method string              getTitle()            Returns the current record's "title" value
 * @method string              getCover()            Returns the current record's "cover" value
 * @method string              getDirector()         Returns the current record's "director" value
 * @method integer             getAddressId()        Returns the current record's "address_id" value
 * @method Doctrine_Collection getActor()            Returns the current record's "Actor" collection
 * @method Address             getAddress()          Returns the current record's "Address" value
 * @method Doctrine_Collection getBookingPassenger() Returns the current record's "BookingPassenger" collection
 * @method Booking             setTitle()            Sets the current record's "title" value
 * @method Booking             setCover()            Sets the current record's "cover" value
 * @method Booking             setDirector()         Sets the current record's "director" value
 * @method Booking             setAddressId()        Sets the current record's "address_id" value
 * @method Booking             setActor()            Sets the current record's "Actor" collection
 * @method Booking             setAddress()          Sets the current record's "Address" value
 * @method Booking             setBookingPassenger() Sets the current record's "BookingPassenger" collection
 * 
 * @package    hyplexdemo
 * @subpackage model
 * @author     David Maignan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBooking extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('booking');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cover', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('director', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('address_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Passenger as Actor', array(
             'refClass' => 'BookingPassenger',
             'local' => 'booking_id',
             'foreign' => 'passenger_id'));

        $this->hasOne('Address', array(
             'local' => 'address_id',
             'foreign' => 'id'));

        $this->hasMany('BookingPassenger', array(
             'local' => 'id',
             'foreign' => 'booking_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}