<?php

/**
 * BaseTopDestination
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $filename
 * @property integer $rank
 * @property timestamp $start_at
 * @property timestamp $expires_at
 * @property boolean $published
 * @property boolean $archived
 * 
 * @method string         getName()       Returns the current record's "name" value
 * @method string         getFilename()   Returns the current record's "filename" value
 * @method integer        getRank()       Returns the current record's "rank" value
 * @method timestamp      getStartAt()    Returns the current record's "start_at" value
 * @method timestamp      getExpiresAt()  Returns the current record's "expires_at" value
 * @method boolean        getPublished()  Returns the current record's "published" value
 * @method boolean        getArchived()   Returns the current record's "archived" value
 * @method TopDestination setName()       Sets the current record's "name" value
 * @method TopDestination setFilename()   Sets the current record's "filename" value
 * @method TopDestination setRank()       Sets the current record's "rank" value
 * @method TopDestination setStartAt()    Sets the current record's "start_at" value
 * @method TopDestination setExpiresAt()  Sets the current record's "expires_at" value
 * @method TopDestination setPublished()  Sets the current record's "published" value
 * @method TopDestination setArchived()   Sets the current record's "archived" value
 * 
 * @package    hyplexdemo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTopDestination extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('top_destination');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('rank', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('start_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('expires_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('published', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('archived', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}