<?php

/**
 * Basepms_milestone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property timestamp $due_date
 * @property Doctrine_Collection $Milestones
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method timestamp           getDueDate()    Returns the current record's "due_date" value
 * @method Doctrine_Collection getMilestones() Returns the current record's "Milestones" collection
 * @method pms_milestone       setName()       Sets the current record's "name" value
 * @method pms_milestone       setDueDate()    Sets the current record's "due_date" value
 * @method pms_milestone       setMilestones() Sets the current record's "Milestones" collection
 * 
 * @package    hypertech_booking
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepms_milestone extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pms_milestone');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('due_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('pms_ticket as Milestones', array(
             'local' => 'id',
             'foreign' => 'pms_milestone_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}