<?php

/**
 * BaseCityMultipleAirport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $city_id
 * @property integer $city_metro_id
 * @property City $City
 * @property City_metro $City_metro
 * 
 * @method integer             getCityId()        Returns the current record's "city_id" value
 * @method integer             getCityMetroId()   Returns the current record's "city_metro_id" value
 * @method City                getCity()          Returns the current record's "City" value
 * @method City_metro          getCityMetro()     Returns the current record's "City_metro" value
 * @method CityMultipleAirport setCityId()        Sets the current record's "city_id" value
 * @method CityMultipleAirport setCityMetroId()   Sets the current record's "city_metro_id" value
 * @method CityMultipleAirport setCity()          Sets the current record's "City" value
 * @method CityMultipleAirport setCityMetro()     Sets the current record's "City_metro" value
 * 
 * @package    hyplexdemo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCityMultipleAirport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('city_multiple_airport');
        $this->hasColumn('city_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('city_metro_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('City', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('City_metro', array(
             'local' => 'city_metro_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}