<?php

/**
 * BaseIpMapping
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ip_from
 * @property integer $ip_to
 * @property integer $country_id
 * @property string $country_code
 * @property Country $Country
 * 
 * @method integer   getIpFrom()       Returns the current record's "ip_from" value
 * @method integer   getIpTo()         Returns the current record's "ip_to" value
 * @method integer   getCountryId()    Returns the current record's "country_id" value
 * @method string    getCountryCode()  Returns the current record's "country_code" value
 * @method Country   getCountry()      Returns the current record's "Country" value
 * @method IpMapping setIpFrom()       Sets the current record's "ip_from" value
 * @method IpMapping setIpTo()         Sets the current record's "ip_to" value
 * @method IpMapping setCountryId()    Sets the current record's "country_id" value
 * @method IpMapping setCountryCode()  Sets the current record's "country_code" value
 * @method IpMapping setCountry()      Sets the current record's "Country" value
 * 
 * @package    hyplexdemo
 * @subpackage model
 * @author     David Maignan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIpMapping extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ip_mapping');
        $this->hasColumn('ip_from', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ip_to', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('country_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('country_code', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id'));
    }
}