<?php

/**
 * Basepms_attachement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pms_ticket_id
 * @property string $filename
 * @property pms_ticket $PmsTicket
 * 
 * @method integer         getPmsTicketId()   Returns the current record's "pms_ticket_id" value
 * @method string          getFilename()      Returns the current record's "filename" value
 * @method pms_ticket      getPmsTicket()     Returns the current record's "PmsTicket" value
 * @method pms_attachement setPmsTicketId()   Sets the current record's "pms_ticket_id" value
 * @method pms_attachement setFilename()      Sets the current record's "filename" value
 * @method pms_attachement setPmsTicket()     Sets the current record's "PmsTicket" value
 * 
 * @package    hypertech_booking
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepms_attachement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pms_attachement');
        $this->hasColumn('pms_ticket_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('pms_ticket as PmsTicket', array(
             'local' => 'pms_ticket_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}