<?php

/**
 * BaseRequestInitPlex
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $date
 * @property string $user_culture
 * @property string $user_ip
 * @property string $user_agent
 * @property string $user_folder
 * @property decimal $elapsed_time
 * @property string $header
 * @property int $response_code
 * @property clob $response_raw
 * @property string $stid
 * 
 * @method timestamp       getDate()          Returns the current record's "date" value
 * @method string          getUserCulture()   Returns the current record's "user_culture" value
 * @method string          getUserIp()        Returns the current record's "user_ip" value
 * @method string          getUserAgent()     Returns the current record's "user_agent" value
 * @method string          getUserFolder()    Returns the current record's "user_folder" value
 * @method decimal         getElapsedTime()   Returns the current record's "elapsed_time" value
 * @method string          getHeader()        Returns the current record's "header" value
 * @method int             getResponseCode()  Returns the current record's "response_code" value
 * @method clob            getResponseRaw()   Returns the current record's "response_raw" value
 * @method string          getStid()          Returns the current record's "stid" value
 * @method RequestInitPlex setDate()          Sets the current record's "date" value
 * @method RequestInitPlex setUserCulture()   Sets the current record's "user_culture" value
 * @method RequestInitPlex setUserIp()        Sets the current record's "user_ip" value
 * @method RequestInitPlex setUserAgent()     Sets the current record's "user_agent" value
 * @method RequestInitPlex setUserFolder()    Sets the current record's "user_folder" value
 * @method RequestInitPlex setElapsedTime()   Sets the current record's "elapsed_time" value
 * @method RequestInitPlex setHeader()        Sets the current record's "header" value
 * @method RequestInitPlex setResponseCode()  Sets the current record's "response_code" value
 * @method RequestInitPlex setResponseRaw()   Sets the current record's "response_raw" value
 * @method RequestInitPlex setStid()          Sets the current record's "stid" value
 * 
 * @package    hypertech_booking
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRequestInitPlex extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('request_init_plex');
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('user_culture', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('user_ip', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('user_agent', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('user_folder', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('elapsed_time', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             'scale' => 14,
             ));
        $this->hasColumn('header', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('response_code', 'int', null, array(
             'type' => 'int',
             'notnull' => true,
             ));
        $this->hasColumn('response_raw', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('stid', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}