<?php

/**
 * BaseHotelCities
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hotel_id
 * @property integer $city_id
 * @property Hotel $Hotel
 * @property City $City
 * 
 * @method integer     getHotelId()  Returns the current record's "hotel_id" value
 * @method integer     getCityId()   Returns the current record's "city_id" value
 * @method Hotel       getHotel()    Returns the current record's "Hotel" value
 * @method City        getCity()     Returns the current record's "City" value
 * @method HotelCities setHotelId()  Sets the current record's "hotel_id" value
 * @method HotelCities setCityId()   Sets the current record's "city_id" value
 * @method HotelCities setHotel()    Sets the current record's "Hotel" value
 * @method HotelCities setCity()     Sets the current record's "City" value
 * 
 * @package    hyplexdemo
 * @subpackage model
 * @author     David Maignan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHotelCities extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hotel_cities');
        $this->hasColumn('hotel_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('city_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Hotel', array(
             'local' => 'hotel_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('City', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}