<?php

/**
 * BasePromotionalBanner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $filename
 * @property string $message
 * @property string $color_bg
 * @property enum $position
 * @property integer $rank
 * @property timestamp $start_at
 * @property timestamp $expires_at
 * @property boolean $published
 * @property boolean $archived
 * @property string $link
 * 
 * @method string            getFilename()   Returns the current record's "filename" value
 * @method string            getMessage()    Returns the current record's "message" value
 * @method string            getColorBg()    Returns the current record's "color_bg" value
 * @method enum              getPosition()   Returns the current record's "position" value
 * @method integer           getRank()       Returns the current record's "rank" value
 * @method timestamp         getStartAt()    Returns the current record's "start_at" value
 * @method timestamp         getExpiresAt()  Returns the current record's "expires_at" value
 * @method boolean           getPublished()  Returns the current record's "published" value
 * @method boolean           getArchived()   Returns the current record's "archived" value
 * @method string            getLink()       Returns the current record's "link" value
 * @method PromotionalBanner setFilename()   Sets the current record's "filename" value
 * @method PromotionalBanner setMessage()    Sets the current record's "message" value
 * @method PromotionalBanner setColorBg()    Sets the current record's "color_bg" value
 * @method PromotionalBanner setPosition()   Sets the current record's "position" value
 * @method PromotionalBanner setRank()       Sets the current record's "rank" value
 * @method PromotionalBanner setStartAt()    Sets the current record's "start_at" value
 * @method PromotionalBanner setExpiresAt()  Sets the current record's "expires_at" value
 * @method PromotionalBanner setPublished()  Sets the current record's "published" value
 * @method PromotionalBanner setArchived()   Sets the current record's "archived" value
 * @method PromotionalBanner setLink()       Sets the current record's "link" value
 * 
 * @package    hyplexdemo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePromotionalBanner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('promotional_banner');
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('message', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('color_bg', 'string', 10, array(
             'type' => 'string',
             'default' => '#FFFFFF',
             'length' => 10,
             ));
        $this->hasColumn('position', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'left',
              1 => 'right',
             ),
             ));
        $this->hasColumn('rank', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('start_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('expires_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('published', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('archived', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'message',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}