<?php

/**
 * BaseState
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property integer $country_id
 * @property Country $Country
 * @property City $Cities
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method string  getCode()       Returns the current record's "code" value
 * @method string  getName()       Returns the current record's "name" value
 * @method integer getCountryId()  Returns the current record's "country_id" value
 * @method Country getCountry()    Returns the current record's "Country" value
 * @method City    getCities()     Returns the current record's "Cities" value
 * @method State   setId()         Sets the current record's "id" value
 * @method State   setCode()       Sets the current record's "code" value
 * @method State   setName()       Sets the current record's "name" value
 * @method State   setCountryId()  Sets the current record's "country_id" value
 * @method State   setCountry()    Sets the current record's "Country" value
 * @method State   setCities()     Sets the current record's "Cities" value
 * 
 * @package    hyplexdemo
 * @subpackage model
 * @author     David Maignan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseState extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('state');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('code', 'string', 3, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 3,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('country_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('country_id_index', array(
             'fields' => 
             array(
              0 => 'country_id',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('City as Cities', array(
             'local' => 'id',
             'foreign' => 'state_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => false,
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($i18n0);
    }
}