# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  languages:
    available: [en_US, fr_FR, zh_CN]

  cookie:
    duration: 260000

  currency: USD
  
  moduleaction:
    colors:
      searchFlight:
        searchAgain: blue
        create: blue
      searchHotel:
        searchAgain: blue
        create: blue
      basket:
        add: green
        remove: red
      flight:
        filterFlight: grey2
        flightResult: yellow
        selected: green
      hotel:
        filterHotel: grey2
        hotelResult: yellow
        selected: green
      main:
        index: grey
      session:
        renewStid: purple
