browserPieChart:
  url: /:sf_culture/stats/browser
  param: { module: historic, action: browserPieChart }
  requirements: { sf_culture: (?:en_US|fr_FR|zh_CN) }
  
hourlyChart:
  url: /:sf_culture/stats/hourly
  param: { module: historic, action: hourlyChart }
  requirements: { sf_culture: (?:en_US|fr_FR|zh_CN) }
  
historic_daily_user:
  url: /:sf_culture/stats/daily/user-activity
  param: {module: historic, action: dailyUser }
  requirements: { sf_culture: (?:en_US|fr_FR|zh_CN) }

historic_daily:
  url: /:sf_culture/stats/daily
  param: {module: historic, action: daily }
  requirements: { sf_culture: (?:en_US|fr_FR|zh_CN) }
  
historic_moveToDB:
  url:   /:sf_culture/stats-move-to-db
  param: { module: historic, action: moveToDB }
  requirements: { sf_culture: (?:en_US|fr_FR|zh_CN) }
  
historic_day:
  url:   /:sf_culture/stats-per-day
  param: { module: historic, action: statsPerDay }
  requirements: { sf_culture: (?:en_US|fr_FR|zh_CN) }

historic:
  class: sfDoctrineRouteCollection
  options:
    model:                Historic
    module:               historic
    prefix_path:          /:sf_culture/stats
    column:               id
    with_wildcard_routes: true
    requirements: { sf_culture: (?:en_US|fr_FR|zh_CN) }

promotional_banner:
  class: sfDoctrineRouteCollection
  options:
    model:                PromotionalBanner
    module:               promotionalBanner
    prefix_path:          /:sf_culture/promotionalBanner
    column:               id
    with_wildcard_routes: true
    requirements: { sf_culture: (?:en_US|fr_FR|zh_CN) }

airline:
  class: sfDoctrineRouteCollection
  options:
    model:                Airline
    module:               airline
    prefix_path:          /:sf_culture/airline
    column:               id
    with_wildcard_routes: true
    requirements: { sf_culture: (?:en_US|fr_FR|zh_CN) }

city_metro:
  class: sfDoctrineRouteCollection
  options:
    model:                City_metro
    module:               citymetro
    prefix_path:          /:sf_culture/citymetro
    column:               id
    with_wildcard_routes: true

city:
  class: sfDoctrineRouteCollection
  options:
    model:                City
    module:               city
    prefix_path:          /:sf_culture/city
    column:               id
    with_wildcard_routes: true

state:
  class: sfDoctrineRouteCollection
  options:
    model:                State
    module:               state
    prefix_path:          /:sf_culture/state
    column:               id
    with_wildcard_routes: true

country:
  class: sfDoctrineRouteCollection
  options:
    model:                Country
    module:               country
    prefix_path:          /:sf_culture/country
    column:               id
    with_wildcard_routes: true

area:
  class: sfDoctrineRouteCollection
  options:
    model:                Area
    module:               area
    prefix_path:          /:sf_culture/area
    column:               id
    with_wildcard_routes: true

booking:
  class: sfDoctrineRouteCollection
  options:
    model:                booking
    module:               booking
    prefix_path:          /:sf_culture/booking
    column:               id
    with_wildcard_routes: true

sf_error_log:
  class: sfDoctrineRouteCollection
  options:
    model:                sfErrorLog
    module:               sferrorlog
    prefix_path:          /:sf_culture/sferrorlog
    column:               id
    with_wildcard_routes: true

request_init_plex:
  class: sfDoctrineRouteCollection
  options:
    model:                RequestInitPlex
    module:               initrequest
    prefix_path:          /:sf_culture/initrequest
    column:               id
    with_wildcard_routes: true

view_plex_error:
  url: /:sf_culture/plexerror/
  param: { module: plexerror, action: viewErrorFile }

plex_error_log:
  class: sfDoctrineRouteCollection
  options:
    model:                plexErrorLog
    module:               plexerror
    prefix_path:          /:sf_culture/plexerror
    column:               id
    with_wildcard_routes: true

request_plex:
  class: sfDoctrineRouteCollection
  options:
    model:                RequestPlex
    module:               plexrequest
    prefix_path:          /:sf_culture/plexrequest
    column:               id
    with_wildcard_routes: true

sf_guard_group:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardGroup
    module:               sfGuardGroup
    prefix_path:          /:sf_culture/groups
    column:               id
    with_wildcard_routes: true
    requirements: { sf_culture: (?:en_US|fr_FR|zh_CN) }

sf_guard_permission:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardPermission
    module:               sfGuardPermission
    prefix_path:          /:sf_culture/permissions
    column:               id
    with_wildcard_routes: true
    requirements: { sf_culture: (?:en_US|fr_FR|zh_CN) }

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               user
    prefix_path:          /:sf_culture/user
    column:               id
    with_wildcard_routes: true
    requirements: { sf_culture: (?:en_US|fr_FR|zh_CN) }

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules

localized_homepage:
  url:   /:sf_culture/
  param: { module: dashboard, action: index }
  requirements: { sf_culture: (?:en_US|fr_FR|zh_CN) }

homepage:
  url:   /
  param: { module: dashboard, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:sf_culture/:module/:action/*
