<?php

/**
 * PluginplexErrorLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginplexErrorLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginplexErrorLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginplexErrorLog');
    }
}