<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfErrorLog extends BasesfErrorLog
{
  public function getExceptionObject()
  {
    return @unserialize($this->_get('exception_object'));
  }

  public function setExceptionObject($exception)
  {
    $this->_set('exception_object', serialize($exception));
  }

  public function getRequest()
  {
    return @unserialize($this->_get('request'));
  }

  public function setRequest($request)
  {
    $this->_set('request', serialize($request));
  }
}