<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfErrorLogTable extends Doctrine_Table
{
  static public function deleteAllSimilar($error)
  {
    if (is_null($error))
    {
      return;
    }

    $q = Doctrine_Query::create()
    	->delete()
    	->from('sfErrorLog')
    	->addWhere('type = ?', $error->get('type'))
    	->addWhere('class_name = ?', $error->get('class_name'))
    	->addWhere('module_name = ?', $error->get('module_name'))
    	->addWhere('action_name = ?', $error->get('action_name'))
    	->addWhere('message = ?', $error->get('message'))
    	->addWhere('uri = ?', $error->get('uri'));
    	
     $q->execute();
  }
}