<?php

/**
 * AirlineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AirlineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AirlineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Airline');
    }

    public function saveList($array)
    {
        foreach ($array as $key => $value) {
            $airline = new Airline();
            $airline->setTag($key);
            $airline->setName($value);
            try{
                $airline->save();
            }  catch (Doctrine_Exception $e){
                
            }
        }

    }


}