<?php

/**
 * Booking
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hyplexdemo
 * @subpackage model
 * @author     David Maignan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Booking extends BaseBooking
{
     public function saveBooking(PlexBooking $booking, $userId){

        $bookingId = $booking->getBookingId();

        $this->setBookingId($bookingId);
        $this->setObject($booking);
        $this->setUserId($userId);
        try{
            $this->save();
        }catch(Doctrine_Exception $e){
            //echo $e->__toString();
            //exit;
        }


    }

}
