<?php

/**
 * BookingPassengerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BookingPassengerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BookingPassengerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BookingPassenger');
    }
}