<?php

/**
 * City_metroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class City_metroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object City_metroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('City_metro');
    }
}