<?php

/**
 * City_metro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hypertech_booking
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class City_metro extends BaseCity_metro
{

    public function  save(Doctrine_Connection $conn = null) {


        


        if($this->isNew()){

            echo $this->getCityMetroId();

            $q = Doctrine_Query::create()
                        ->update('City')
                        ->set('metropolitan', true)
                        ->where('id = ?', $this->getCityMetroId())
                        ->execute();

        }

        //break;

        parent::save($conn);

    }


    public function  delete(Doctrine_Connection $conn = null) {

        $this->getCityMetroId();

        $q = Doctrine_Query::create()
                        ->update('City')
                        ->set('metropolitan', false)
                        ->where('id = ?', $this->getCityMetroId())
                        ->execute();

        parent::delete($conn);
    }


}
