<?php

/**
 * City
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hypertech_booking
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class City extends BaseCity
{

  public function cacheOrUncache()
  {

    $bol = $this->getCache();
    $this->setCache(!$bol);
    $this->save();

    return true;
  }

  public function getFullAddress(){

      return $this->getCode() . ' '.
              ' '.$this->getAirport().
              ' '.$this->getName() .
              ' '.$this->getState().
              ' '.$this->getCountry();

  }


}
