<?php

/**
 * CityMultipleAirportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CityMultipleAirportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CityMultipleAirportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CityMultipleAirport');
    }
}