<?php

/**
 * CountryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CountryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CountryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Country');
    }

    public function applyNameFilter($query, $value) {

        $query->leftJoin($query->getRootAlias() . '.Translation t')
                ->addWhere('t.name like \'%' . $value['text'] . '%\'');
    }


    public function searchAutoComplete($value){

        $culture = sfContext::getInstance()->getUser()->getCulture();

        $value = $value.'%';

        $q = Doctrine::getTable('country')
                ->createQuery('a')
                ->select('a.id, t.name AS name')
                ->leftJoin('a.Translation t')
                ->andWhere('t.lang = ?', $culture)
                ->addWhere('t.name LIKE ?', $value)
                ->execute(array(), Doctrine_Core::HYDRATE_SCALAR);

        return $q;

    }



}