<?php

/**
 * HotelFacilityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HotelFacilityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HotelFacilityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HotelFacility');
    }
}