<?php

/**
 * HotelCitiesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HotelCitiesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HotelCitiesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HotelCities');
    }
}