<?php

/**
 * IpMappingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IpMappingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IpMappingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IpMapping');
    }
    
    
    public function getCountryIdFromIps($values){
    	
    	//Convert ips to numeric values
    	$b = array_map("Utils::convertIpToNumeric", $values);
    	//$b = array_map(array("Utils","convertIpToNumeric"), $values);
    	
    	$q = Doctrine_Query::create()
    			->from('IpMapping a')
    			->where('a.ip_from < ? AND a.ip_to > ?', array($b[0],$b[0]));
    	for($i=1;$i<count($values);$i++){
    		$q->orWhere('a.ip_from < ? AND a.ip_to > ?', array($b[$i],$b[$i]));
    	}
    			
    	$results = $q->execute()->toArray();
    	
    	return $results;
    }
}