<?php

/**
 * PassengerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PassengerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PassengerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Passenger');
    }
}