<?php

/**
 * pms_ticketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class pms_ticketTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object pms_ticketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('pms_ticket');
    }
}