<?php

/**
 * pms_milestoneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class pms_milestoneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object pms_milestoneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('pms_milestone');
    }
}