<?php

/**
 * pms_attachementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class pms_attachementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object pms_attachementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('pms_attachement');
    }
}