<?php

/**
 * pms_clarificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class pms_clarificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object pms_clarificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('pms_clarification');
    }
}