<?php

/**
 * pms_email_logTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class pms_email_logTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object pms_email_logTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('pms_email_log');
    }
}