<?php

/**
 * PromotionalBannerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PromotionalBannerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PromotionalBannerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PromotionalBanner');
    }

    public function getActivePromotions($culture)
    {
        $today = (date('Y-m-d H:i:s'));

        $q = Doctrine_Query::create()
                        ->select('a.filename, a.position, a.color_bg, a.link, t.message AS message')
                        ->from('PromotionalBanner a')
                        ->leftJoin('a.Translation t')
                        ->andWhere('a.published = ?',1)
                        ->andWhere('a.archived = ?',0)
                        ->andwhere('t.lang = ?',$culture)
                        ->andWhere('a.start_at <= ?', $today)
                        ->andWhere('a.expires_at >= ?', $today)
                        ->orderBy('a.rank ASC')
                        ->execute()
                        ->toArray();

        

        return $q;


    }

     public static function getMaxRank() {
        $last_rank = Doctrine_Query::create()
                ->select('u.rank')
                ->from('PromotionalBanner u')
                ->orderBy('u.rank DESC')
                ->limit(1)
                ->execute()
                ->toArray();

        return($last_rank[0]['rank']);

    }

}