<?php

/**
 * RequestInitPlexTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RequestInitPlexTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RequestInitPlexTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RequestInitPlex');
    }
}