<?php

/**
 * RequestPlexTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RequestPlexTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RequestPlexTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RequestPlex');
    }
}