<?php

/**
 * TopDestinationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TopDestinationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TopDestinationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TopDestination');
    }

    public static function getMaxRank() {
        $last_rank = Doctrine_Query::create()
                ->select('u.rank')
                ->from('TopDestination u')
                ->orderBy('u.rank DESC')
                ->limit(1)
                ->execute()
                ->toArray();

        return($last_rank[0]['rank']);

    }
}