# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  plex:
    url: http://test.hypertechsolutions.com/ipm2/services/PlexConnect
    location: http://test.hypertechsolutions.com/ipm/services/PlexConnect
    uri: http://plexconnect.ipm.hypertechsolutions.com
    transactionId: TRANS101
    systemName: Test
    companyId: STD
    partnerId: STD
    username: wstest
    password: wstest01

  plex2:
    url: http://test.hypertechsolutions.com/ipm3/services/PlexConnect
    location: http://test.hypertechsolutions.com/ipm/services/PlexConnect
    uri: http://plexconnect.ipm.hypertechsolutions.com
    transactionId: TRANS101
    systemName: Test
    companyId: PCS
    partnerId: PCS
    username: admin
    password: travel
    
  plex3:
    url: http://test.hypertechsolutions.com/ipm/services/PlexConnect
    location: http://test.hypertechsolutions.com/ipm/services/PlexConnect
    uri: http://plexconnect.ipm.hypertechsolutions.com
    transactionId: TRANS101
    systemName: Test
    companyId: STD
    partnerId: STD
    username: wstest
    password: wstest01

  sf_guard_plugin:
    remember_cookie_name:   HypertechRememberMe


  sf_guard_plugin:
    routes_register: false

  languages:
    available: [zh_CN, fr_FR , en_US]

  currency:
    available: [USD, GDB, EURO, CAD, CHF]
    
  currencies:
    array:
      USD: American dollar (USD)
      EURO: Euro (EUR)
      GBP: British Pound (GBP)
      AUD: Australian dollar (AUD)
      CAD: Canadian dollar (CAD)
      YEN: Japanese Yen (YEN)
      
  langues:
    array:
      en_US: English (US)
      fr_FR: Francais (Fr)
      zh_CN: Chinese (Zh)

  cookie:
    duration: 260000

  plexSession:
#    duration: 900
    duration: 600

  layout:
    template: test

  hotel:
    numberAdults: 6
    numberChildren: 6
    thumb:
      width: 150
      height: 105

  currency: USD

  telephone: 1 800 123 4567
    
  special:
    assistance: [ '' ,Can walk to seat, Can walk up stairs, Dry Cell Battery, Manual Power, Must be carried, On Board, Wet Cell Battery]

  creditcard:
    accepted: [Mastercard, Visa, American Express]
    
  totalPerPage: 10
