generator:
  class: sfDoctrineGenerator
  param:
    model_class:           plexErrorLog
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          plex_error_log
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [id, created_at, type, class_name, message, plex_response, _file]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
