generator:
  class: sfDoctrineGenerator
  param:
    model_class:           RequestInitPlex
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          request_init_plex
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [date, user_ip, user_agent, user_culture, user_folder, response_code, elapsed_time]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
