generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfErrorLog
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_error_log
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:   
        display: [id, type, class_name, message, module_name, action_name, exception_object ]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
