generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Airline
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          airline
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [ _icon, tag, name ]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
