<?php

/**
 * BasesfErrorLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * @property string $class_name
 * @property string $message
 * @property string $module_name
 * @property string $action_name
 * @property clob $exception_object
 * @property clob $request
 * @property string $uri
 * 
 * @method integer    getId()               Returns the current record's "id" value
 * @method string     getType()             Returns the current record's "type" value
 * @method string     getClassName()        Returns the current record's "class_name" value
 * @method string     getMessage()          Returns the current record's "message" value
 * @method string     getModuleName()       Returns the current record's "module_name" value
 * @method string     getActionName()       Returns the current record's "action_name" value
 * @method clob       getExceptionObject()  Returns the current record's "exception_object" value
 * @method clob       getRequest()          Returns the current record's "request" value
 * @method string     getUri()              Returns the current record's "uri" value
 * @method sfErrorLog setId()               Sets the current record's "id" value
 * @method sfErrorLog setType()             Sets the current record's "type" value
 * @method sfErrorLog setClassName()        Sets the current record's "class_name" value
 * @method sfErrorLog setMessage()          Sets the current record's "message" value
 * @method sfErrorLog setModuleName()       Sets the current record's "module_name" value
 * @method sfErrorLog setActionName()       Sets the current record's "action_name" value
 * @method sfErrorLog setExceptionObject()  Sets the current record's "exception_object" value
 * @method sfErrorLog setRequest()          Sets the current record's "request" value
 * @method sfErrorLog setUri()              Sets the current record's "uri" value
 * 
 * @package    hypertech_booking
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfErrorLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_error_log');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('type', 'string', 3, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 3,
             ));
        $this->hasColumn('class_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('message', 'string', 1000000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000000,
             ));
        $this->hasColumn('module_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('action_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('exception_object', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('request', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('uri', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}