<?php

/**
 * plexErrorLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class plexErrorLogTable extends PluginplexErrorLogTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object plexErrorLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('plexErrorLog');
    }
}