<?php

/**
 * sfErrorLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfErrorLogTable extends PluginsfErrorLogTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfErrorLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfErrorLog');
    }
}